language: cpp

dist: bionic

cache:
    - pip
before_install:
    - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    - git fetch origin master
install:
    - sudo bash -c 'echo "deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe" >> /etc/apt/sources.list'
    - sudo bash -c 'echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe" >> /etc/apt/sources.list'
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake qt5-default
    - cmake --version
    - pip install cpplint
script:
    - cpplint --recursive --root="DnD/include" --filter=-legal/copyright,-readability/todo,-whitespace/line_length,-runtime/threadsafe_fn,-build/header_guard,-build/include_subdir,-whitespace/comments,-whitespace/indent,-readability/alt_tokens  DnD/
    - cd DnD/build
    - cmake ..
    - make
